### ISSUE TITLE
expose which GTFS feed is being used

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/hafas-gtfs-rt-feed#11]
@felixguendling noted that it's hard to use a GTFS-RT feed without knowing exactly which GTFS feed it matches to.

Because transit operators/authorities frequently publish new GTFS datasets without stable IDs (e.g. the same route might have a different ID, because IDs get generated just be enumerating all routes in an undefined order), and because the operator of a `hafas-gtfs-rt-feed` instance might switch to the latest GTFS dataset at any time, the IDs within the GTFS-RT feed are effectively unusable.

Some ideas:

- Serve the GTFS dataset's `feed_info.txt` via HTTP, which [must contain `feed_publisher_name`](https://gtfs.org/reference/static#feed_infotxt) and [should contain `feed_start_date`, `feed_end_date` & `feed_version`](https://gtfs.org/best-practices/#feed_infotxt).
- Service the GTFS dataset's hash via HTTP.
- Service the GTFS dataset's publication date via HTTP.

**Comment by felixguendling** [comment]
I think these ideas would work. Another idea would be to add a download URL so the timetable information system can (1) check whether it has the matching version (2) if not directly download the dataset from the specified URL. However, this requires the GTFS-static timetable data to be available under a public URL without login. Maybe several of these options could be combined.
